# Generated by Django 3.2.9 on 2021-12-13 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
