# Generated by Django 3.2.9 on 2021-12-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20211223_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_joined',
            field=models.DateField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_login',
            field=models.DateField(auto_now=True, verbose_name='last login'),
        ),
    ]
