# Generated by Django 3.2.9 on 2021-12-09 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrderst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False, null=True)),
                ('shipping_method', models.CharField(choices=[('standard', 'standard'), ('fast', 'fast')], default='standard', max_length=50)),
                ('AWB_NO', models.CharField(max_length=100)),
                ('payment_gateway_id', models.IntegerField()),
                ('transaction_id', models.CharField(max_length=100)),
                ('created_date', models.DateField(auto_now=True)),
                ('status', models.BooleanField()),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('shipping_charges', models.DecimalField(decimal_places=2, max_digits=12)),
                ('billing_address_1', models.CharField(blank=True, max_length=100)),
                ('billing_address_2', models.CharField(blank=True, max_length=100)),
                ('billing_city', models.CharField(blank=True, max_length=45)),
                ('billing_state', models.CharField(blank=True, max_length=45)),
                ('billing_country', models.CharField(blank=True, max_length=45)),
                ('billing_zipcode', models.CharField(blank=True, max_length=45)),
                ('shipping_address_1', models.CharField(blank=True, max_length=100)),
                ('shipping_address_2', models.CharField(blank=True, max_length=100)),
                ('shipping_city', models.CharField(blank=True, max_length=45)),
                ('shipping_state', models.CharField(blank=True, max_length=45)),
                ('shipping_country', models.CharField(blank=True, max_length=45)),
                ('shipping_zipcode', models.CharField(blank=True, max_length=45)),
                ('coupon_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.coupons')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.userorderst')),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
