# Generated by Django 3.2.9 on 2021-12-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
