# Generated by Django 3.2.9 on 2021-12-11 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_productimages_image'),
        ('customer', '0001_initial'),
        ('orders', '0002_orderdetails_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserOrderst',
            new_name='UserOrder',
        ),
    ]
