# Generated by Django 3.2.9 on 2021-12-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_userorderst_userorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
