# Generated by Django 3.2.9 on 2021-12-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_userorder_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='AWB_NO',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='billing_address_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='billing_address_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='billing_city',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='billing_country',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='billing_state',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='billing_zipcode',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='created_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='payment_gateway_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='shipping_address_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='shipping_address_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='shipping_charges',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='shipping_country',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='shipping_method',
            field=models.CharField(choices=[('standard', 'standard'), ('fast', 'fast')], default='standard', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='shipping_state',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='shipping_zipcode',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
