# Generated by Django 3.2.9 on 2021-12-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20211213_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
