# Generated by Django 3.2.9 on 2021-12-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_orderdetails_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Price'),
        ),
    ]
