# Generated by Django 3.2.9 on 2021-12-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_remove_wishlist_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='grand_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
