# Generated by Django 3.2.9 on 2021-12-21 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_userorder_grand_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='transaction_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
