# Generated by Django 3.2.9 on 2021-12-22 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_userorder_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='user',
            new_name='customer',
        ),
    ]
