# Generated by Django 3.2.9 on 2021-12-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_rename_user_wishlist_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='status',
            field=models.CharField(choices=[('placed', 'Placed'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='placed', max_length=50, null=True),
        ),
    ]
