# Generated by Django 3.2.9 on 2021-12-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_userorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Paid', 'Paid'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], default='placed', max_length=50, null=True),
        ),
    ]
