# Generated by Django 3.2.9 on 2021-12-17 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_productimages_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupons',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='coupons',
            name='valid_to',
        ),
    ]
